openpose:
  root: "/home/bohdan/openpose"
  hand: false
  face: false
  net_resolution: "-1x256"
  num_gpu: 1
  num_gpu_start: 0
  render_pose: 0
  disable_blending: true
  number_people_max: -1
  disable_multi_thread: true

data:
  input_dir: "/home/bohdan/2026-06-07 15-48-35.mp4"
  save_width: 800
  save_dir: "data/output/test"

restore_mode: true
save_log: true

stages:
  preprocessing: true
  detection_preparation: true
  local_tracking: true
  local_det_saving: true
  global_clustering: true
  global_saving: true


preprocessing:
  batch_size: 256
  checkpoint_every_frames: 100
  save_crops: auto

detection_preparation:
  batch_size: 256

local_tracking:
  batch_size: 500
  checkpoint_every_frames: 50

local_det_saving:
  enabled: false
  batch_size: 700
  matched_dir: matched_dets
  unmatched_dir: unmatched_dets

global_clustering:
  enabled: true
  checkpoint_every_tracks: 10

global_saving:
  enabled: true
  batch_size: 700
  checkpoint_every_frames: 100

progress:
  enabled: true
  library: rich

tracking:
  config_path: "configs/tracking.yaml"
  num_frames_merge: 0
  apperance_embedding_model_path: "models/osnet_appearance.onnx"

shot_boundary:
  config_path: "/home/bohdan/PycharmProjects/Boxing_Tracking_Project/configs/shot_boundary.yaml"
